name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: sudo docker pull furnit/trader:latest
      - name: Delete old docker container
        run: sudo docker rm -f trader-container || true
      - name: Run Docker Container
        run: sudo docker run -d --name trader-container furnit/trader
